
import "./globals.css";
import { AuthProvider } from "./context/Authcontext";
import { UserProvider } from "./context/Usecontext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       
    <AuthProvider>
      <UserProvider>
       {children}
       </UserProvider>
        
   </AuthProvider>
     
     
       
      </body>
    </html>
  );
}
